- hosts: k8s-cluster
  tasks:
    - name: disable swap
      shell: swapoff -a

    - name: update /etc/hosts file
      blockinfile:
        dest: /etc/hosts
        content: "{{ lookup('template', 'templates/etc-hosts.j2') }}"
        state: present

- hosts: k8s-masters
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: k8s-workers
  tasks:
    - name: join cluster
      shell: "{{ hostvars['k8s-master-1'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
